apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: net-utils
  name: net-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-utils
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: net-utils
    spec:
      containers:
      - image: soak47/khoshbin:latest
        name: khoshbin
        resources: {}
status: {}
